@startuml
left to right direction

class User {
    -userName: String
    -firstName: String
    -lastName: String
    -password: String
}

class Recipes {
    -type: String
    -description: String
    -instructions: String
    -cost: Int
}

User "1" --> "create" Recipes
User "2" --> "view all " Recipes


@enduml
